# fly.toml app configuration file generated for mili-umami on 2023-09-03T22:59:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mili-umami"
primary_region = "cdg"

[build]

[build.args]
  DATABASE_TYPE = "postgresql"

[deploy]
  release_command = "yarn check-db"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
